env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_conf: "ENCRYPTED[6ade1bbd9d15265109b65a5d3a7cfe3458dc65d71fd3243da4b947d6d183650fcd50d6c753e32e5baf930f43b59aab35]"

task:
  name: master
  timeout_in: 2h
  only_if: $CIRRUS_REPO_OWNER == 'Doraemon-Kernel'
  container:
    image: dopaemon/bionic:latest
    cpu: 8
    memory: 24G

  Delete_script:
    - rm -rf *
  Install_Packages_Ubuntu_script:
    - sudo apt-get update
    - sudo apt-get install -y ccache rclone git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
  Git_Clone_From_Github_script:
    - cd /tmp/ci
    - git clone -b amd64 --single-branch https://github.com/EternalX-project/aarch64-linux-gnu.git gcc
    - echo "-------------------------------------------------------------------";
    - cd /tmp/ci
    - git clone -b master --single-branch https://github.com/Doraemon-Kernel/android_kernel_samsung_7870.git Linux
  Setup_ENV_script:
    - cd /tmp/ci/Linux
    - touch ~/.compile
    - ./env.sh
  Setup_rclone_config_script:
    - mkdir -p ~/.config/rclone
    - echo "$rclone_conf" > ~/.config/rclone/rclone.conf
  AIK_Unpack_Repack_img_script:
    - cd /tmp/ci/
    - wget https://forum.xda-developers.com/attachments/aik-linux-v3-8-all-tar-gz.5300923/
    - mv index.html aik.tar.gz
    - tar -xf aik.tar.gz
  Compile_script:
    - cd /tmp/ci/Linux/
    - ./build_doraemon.sh

