env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"

    rclone_conf: "ENCRYPTED[6ade1bbd9d15265109b65a5d3a7cfe3458dc65d71fd3243da4b947d6d183650fcd50d6c753e32e5baf930f43b59aab35]"

task:
  name: master
  timeout_in: 2h
  only_if: $CIRRUS_REPO_OWNER == 'Doraemon-Kernel'
  container:
    image: dopaemon/bionic:latest
    cpu: 8
    memory: 24G

  Install_Packages_Ubuntu_script:
    - rm -rf *
    - sudo apt-get update
    - sudo apt-get install -y ccache rclone git-lfs bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
  Git_Clone_From_Github_script:
    - git clone -b amd64 --single-branch https://github.com/EternalX-project/aarch64-linux-gnu.git gcc
    - echo "-------------------------------------------------------------------";
    - git clone -b master --single-branch https://github.com/Doraemon-Kernel/android_kernel_samsung_7870.git kernel
  Compile_Kernel_Treble_script:
    - export ARCH=arm64 && export SUBARCH=arm64
    - cd /tmp/ci/kernel
    - export CCACHE_DIR=/tmp/ccache
    - export CCACHE_EXEC=$(which ccache)
    - export USE_CCACHE=1
    - ccache -M 20G
    - ccache -o compression=true
    - ccache -z
    - ./Doraemon/CI/treble.sh
  Upload_Treble_Google_Drive_script:
    - mkdir -p ~/.config/rclone
    - echo "$rclone_conf" > ~/.config/rclone/rclone.conf
    - cd /tmp/ci/kernel/Doraemon/Product/
    - export DORAEMON="R3.5"
    - export DORAVAR=""
    - export FOLDER="Doraemon-Kernel-$DORAEMON"
    - echo "-------------------------------------------------------------------";
    - rclone copy Doraemon-Kernel-$DORAEMON-A320X-TREBLE.zip drive:Share/Devices/Exynos7870/$FOLDER/Treble/Flashble/
    - rclone copy Doraemon-Kernel-$DORAEMON-A320X-TREBLE.img drive:Share/Devices/Exynos7870/$FOLDER/Treble/Image/
    - rclone copy Doraemon-Kernel-$DORAEMON-A600X-TREBLE.zip drive:Share/Devices/Exynos7870/$FOLDER/Treble/Flashble/
    - rclone copy Doraemon-Kernel-$DORAEMON-A600X-TREBLE.img drive:Share/Devices/Exynos7870/$FOLDER/Treble/Image/
    - rclone copy Doraemon-Kernel-$DORAEMON-G610X-TREBLE.zip drive:Share/Devices/Exynos7870/$FOLDER/Treble/Flashble/
    - rclone copy Doraemon-Kernel-$DORAEMON-G610X-TREBLE.img drive:Share/Devices/Exynos7870/$FOLDER/Treble/Image/
    - rclone copy Doraemon-Kernel-$DORAEMON-J530X-TREBLE.zip drive:Share/Devices/Exynos7870/$FOLDER/Treble/Flashble/
    - rclone copy Doraemon-Kernel-$DORAEMON-J530X-TREBLE.img drive:Share/Devices/Exynos7870/$FOLDER/Treble/Image/
    - rclone copy Doraemon-Kernel-$DORAEMON-J600X-TREBLE.zip drive:Share/Devices/Exynos7870/$FOLDER/Treble/Flashble/
    - rclone copy Doraemon-Kernel-$DORAEMON-J600X-TREBLE.img drive:Share/Devices/Exynos7870/$FOLDER/Treble/Image/
    - rclone copy Doraemon-Kernel-$DORAEMON-J701X-TREBLE.zip drive:Share/Devices/Exynos7870/$FOLDER/Treble/Flashble/
    - rclone copy Doraemon-Kernel-$DORAEMON-J701X-TREBLE.img drive:Share/Devices/Exynos7870/$FOLDER/Treble/Image/
    - rclone copy Doraemon-Kernel-$DORAEMON-J710X-TREBLE.zip drive:Share/Devices/Exynos7870/$FOLDER/Treble/Flashble/
    - rclone copy Doraemon-Kernel-$DORAEMON-J710X-TREBLE.img drive:Share/Devices/Exynos7870/$FOLDER/Treble/Image/
    - rclone copy Doraemon-Kernel-$DORAEMON-J730X-TREBLE.zip drive:Share/Devices/Exynos7870/$FOLDER/Treble/Flashble/
    - rclone copy Doraemon-Kernel-$DORAEMON-J730X-TREBLE.img drive:Share/Devices/Exynos7870/$FOLDER/Treble/Image/
    - echo "-------------------------------------------------------------------";
    - echo "Done"
